name: Build and deploy Python app to Azure Web App - slackbotprod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          
      - name: Install system dependencies for Wordcloud
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip build-essential python3-setuptools python3-wheel libpng-dev libfreetype6-dev

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install Wordcloud
        run: |
          pip install wordcloud-1.8.2.2-py3-none-any.whl
          
      - name: Install Stylecloud
        run: |
          pip install stylecloud-0.5.1-py3-none-any.whl
          
      - name: Install requirements
        run: |
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
            
          # Define the artifact files here
          wordcloud-1.8.2.2-py3-none-any.whl: wordcloud-1.8.2.2-py3-none-any.whl
          stylecloud-0.5.1-py3-none-any.whl: stylecloud-0.5.1-py3-none-any.whl

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          
      - name: Copy deployment script to deployment directory
        run: |
          cp deploy.sh $DEPLOYMENT_TARGET
          
      - name: Make deployment script executable
        run: |
          chmod +x $DEPLOYMENT_TARGET/deploy.sh
          
      - name: Deploy to Azure Web App
        run: |
          cd $DEPLOYMENT_TARGET
          ./deploy.sh
      

